### ISSUE TITLE
Hidden bioconductor dependency(-ies?) is an obstacle for installation/loading

### ISSUE THREAD

**Issue by MattiasErhardsson** [Proteomicslab57357/UniprotR#14]
Hi! I noticed that the bioconductor package GenomicAlignments is a dependency for UniprotR, and unless you have it previously installed with bioconductors special way of installing packages you won't be able to load UniprotR. It took some time for me to figure out why I couldn't load UniprotR nor install GenomicAlignments. For users even more green than me I think it would be helpful to maybe refer to installation of bioconductor packages required for UniprotR under the installation heading.

**Comment by MohmedSoudy** [comment]
It's due to dependency "alakazam" version 1.1.0 while UniprotR requires alakazam version 1.0.0. This problem will be solved in the next version of UniprotR and can be solved now by installing alakazam before installing UniprotR using ```  install.packages("https://cran.r-project.org/src/contrib/Archive/alakazam/alakazam_1.0.0.tar.gz", repo=NULL, type="source")```
