### ISSUE TITLE
GetProteinFunction() does not work.

### ISSUE THREAD

**Issue by MattiasErhardsson** [Proteomicslab57357/UniprotR#15]
GetProteinFunction() yields no data. I have only tested a few other functions, but they work and they are: GetProteinGOInfo(), GetGeneral_Information() and GetPathology_Biotech().

**Comment by MohmedSoudy** [comment]
Dear @MattiasErhardsson The issue is due to renaming some column names by the Uniprot team, we are working on fixing the issue in the next version of UniprotR.

**Comment by benjaminhempel** [comment]
Hello UniporR Team!
I get the following error message when trying to use any command of the UniprotR package:

"Internet_ connection problem occurs and the function will return the original error
Failed to connect to www.uniprot.org port 80: Connection refusedInternet connection problem occurs"

Ich checked the web for any solutions, but could not find any helpful advices? Do you have any ideas to solve the problem?

**Comment by MohmedSoudy** [comment]
Hello benjaminhempel,

Would you tried to re-run the function again? Is the error reproduceable or it's just because a sudden disconnection ?
