### ISSUE TITLE
No package called ‘UniprotR’ after installation

### ISSUE THREAD

**Issue by Xyderal** [Proteomicslab57357/UniprotR#16]
Hi. 
I don't know what I am doing wrong, but 

> install.packages("UniprotR")
Warning in install.packages :
  dependencies ‘Biostrings’, ‘GenomicAlignments’, ‘IRanges’ are not available
also installing the dependency ‘alakazam’

  There are binary versions available but the source versions are later:
         binary source needs_compilation
alakazam  0.3.0  1.1.0              TRUE
UniprotR  1.2.4  2.0.7             FALSE

Do you want to install from sources the package which needs compilation? (Yes/no/cancel) 
installing the source packages ‘alakazam’, ‘UniprotR’

trying URL 'https://cran.rstudio.com/src/contrib/alakazam_1.1.0.tar.gz'
Content type 'application/x-gzip' length 2474294 bytes (2.4 MB)
==================================================
downloaded 2.4 MB

trying URL 'https://cran.rstudio.com/src/contrib/UniprotR_2.0.7.tar.gz'
Content type 'application/x-gzip' length 29544 bytes (28 KB)
==================================================
downloaded 28 KB

ERROR: dependencies ‘Biostrings’, ‘GenomicAlignments’, ‘IRanges’ are not available for package ‘alakazam’
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/alakazam’
Warning in install.packages :
  installation of package ‘alakazam’ had non-zero exit status
ERROR: dependency ‘alakazam’ is not available for package ‘UniprotR’
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/UniprotR’
Warning in install.packages :
  installation of package ‘UniprotR’ had non-zero exit status

The downloaded source packages are in
	‘/private/var/folders/jr/9194sd815yl2zwkz7j2qcy5m0000gn/T/RtmpC3bKdv/downloaded_packages’
> library(UniprotR)
Error in library(UniprotR) : there is no package called ‘UniprotR’
>

I would really want to retrieve information from Uniprot for my Master's assignment. I would really appreciate your help
Antonio

I am using Rstudio Version 1.1.463 with R version 3.5.3 (2019-03-11) -- "Great Truth"
Appreciated

**Comment by MohmedSoudy** [comment]
Dear @Xyderal the issue is similar to #14, it's recommended to install alakazam version 1.0.0 before installing UniprotR.

**Comment by Xyderal** [comment]
Thanks! Working perfectly.
