### ISSUE TITLE
Organsim name for Pathway.Enr

### ISSUE THREAD

**Issue by davidlilek** [Proteomicslab57357/UniprotR#19]
I'm working with data from Tribolium castaneum. Everything went fine with the analysis using UniprotR.

But Pathway.Enr failed due to a error in the organism name.

Tried it this way...
Pathway.Enr(Accessions, OS="tcastaneum")

But it didn't work. Or did this function only work for mouse and humean?

Hope you have any ideas.

Thanks
David

**Comment by MohmedSoudy** [comment]
Hi @davidlilek. Thank you for your interest in Our Package. Could you share the accession list so we can track the problem easier?

**Comment by davidlilek** [comment]
[fasta.csv](https://github.com/Proteomicslab57357/UniprotR/files/9143585/fasta.csv)

Sorry for the delay ;-) Encl. the accesion list I used...

**Comment by MohmedSoudy** [comment]
Hi @davidlilek 
Sorry for  the late reply here is the working code using UniprotR version 2.2.1

```
library(UniprotR)
data <- read.csv(file.choose(), header = F)
Enr <- Pathway.Enr(data$V1, OS="tcastaneum")
```

**Comment by davidlilek** [comment]
Thanks a lot. Don't know why it didn't work at the first try... But now everything fine and it works...
