### ISSUE TITLE
Error installing version 2.2.0

### ISSUE THREAD

**Issue by rjdirven** [Proteomicslab57357/UniprotR#21]
Hi,
I'm quite new to R. Maybe I did something wrong.

I just tried to install UniprotR (install.packages("UniprotR") but it failed. See below.
Maybe you can help me.

Best,
Richard

---

  There is a binary version available but the source version is later:
         binary source needs_compilation
UniprotR  2.1.1  2.2.0             FALSE

installing the source package ‘UniprotR’

trying URL 'https://cran.rstudio.com/src/contrib/UniprotR_2.2.0.tar.gz'
Content type 'application/x-gzip' length 29811 bytes (29 KB)
downloaded 29 KB

* installing *source* package 'UniprotR' ...
** package 'UniprotR' successfully unpacked and MD5 sums checked
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called 'Biostrings'
Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
ERROR: lazy loading failed for package 'UniprotR'

**Comment by AliYoussef96** [comment]
Hi @rjdirven 

Try to install the Biostrings package first.

```R
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("Biostrings")
```
then UniprotR

```R
install.packages("UniprotR")
```

If it doesn't work, give me your OS details, and I will see what the problem is.

**Comment by rjdirven** [comment]
Hi @AliYoussef96 

Thank you very much. 
First, I had to install GenomicAlignments by hand too.
Now everything is fine!!
