### ISSUE TITLE
GetProteinFunction returns 400 Bad Request

### ISSUE THREAD

**Issue by maringos** [Proteomicslab57357/UniprotR#24]
Dear All,

thanks for this software. I would like to report an issue:
When I try your example `Obj <- GetProteinFunction("O14520")`, I get this error back:

```
Please wait we are processing your accessions ...
Warning message:
In file(file, "rt") :
  cannot open URL 'https://rest.uniprot.org/uniprotkb/search?query=accession:O14520&format=tsv&fields=absorption,ft_act_site,cc_activity_regulation,ft_binding,ft_ca_bind,cc_catalytic_activity,cc_cofactor,ft_dna_bind,ec,cc_function,kinetics,ft_metal,ft_np_bind,cc_pathway,ph_dependence,redox_potential,ft_site,temp_dependence': HTTP status was '400 Bad Request'
```
Kind Regards,
Georgios

**Comment by MohmedSoudy** [comment]
Dear Dr. @maringos 
Thank you for your interest in using our package. We update the package to resolve your problem and a new version UniprotR 2.2.1 is on its way to CRAN.
