### ISSUE TITLE
GetproteinNetwork and GetproteinNetwork_all returning errors

### ISSUE THREAD

**Issue by samvgon** [Proteomicslab57357/UniprotR#25]
Given the accession list "IDs", I get the following errors:

> GetproteinNetwork(IDs)

Error in pdf(paste0(directorypath, "/", "Protin Network.pdf")) : 
  cannot open file '/Protin Network.pdf'

> GetproteinNetwork_all(IDs)

Error in pdf(paste0(directorypath, "/", "Whole Protin Network.pdf")) : 
  cannot open file '/Whole Protin Network.pdf'

**Comment by AliYoussef96** [comment]
Hi,

For ```GetproteinNetwork```, you have to specify a directory path where the pdf file will be saved.

example:
```r
GetproteinNetwork(IDs, directorypath = "D:\")
```
