### ISSUE TITLE
Error "Internet connection problem occurs and the function will return original error"

### ISSUE THREAD

**Issue by acragin** [Proteomicslab57357/UniprotR#32]
I am trying to run multiple commands with this package but no matter which I run I keep getting the error:
"Internet connection problem occurs and the function will return the original error
length(url) == 1 is not TRUEInternet connection problem occurs"

when I then do:
`> length(url) == 1
[1] TRUE`
`> length("https://www.uniprot.org/")
[1] 1`

How do I fix this?

**Comment by MohmedSoudy** [comment]
Hi @acragin Thank you for using our package. Could you share the commands that you are trying to run?

**Comment by acragin** [comment]
Hi!

I was trying to run ConvertID, GetAccessionList, and GetGeneral_Informtation, all of which returned the same error as listed before.

**Comment by MohmedSoudy** [comment]
Hi @acragin 
I managed to run the functions ` GetAccessionList ` and `GetGeneral_Informtation` using UniptotR_2.2.2 on Windows 10 using the following script 
```
library(UniprotR)
Accs <- GetAccessionList(file.choose())
potein_general_information <- GetGeneral_Information(Accs)
```
For the `ConvertID` function, please refer to #22 as the solution might be there for the current moment. We will solve this problem in the next release.

**Comment by acragin** [comment]
Hi, 

I tried running that code however I am still receiving the same error message of an internet connection problem occurring. I am trying to run UniprotR_2.2.2 on a mac, could that ver the issue?

**Comment by MohmedSoudy** [comment]
Do you have a stable internet connection while running the codes?

**Comment by acragin** [comment]
Yes I have a stable internet connection

**Comment by MohmedSoudy** [comment]
Hi @acragin ,
 What is the output when you put the following URL to the web browser?
 ```
 https://rest.uniprot.org/uniprotkb/search?query=accession:P05067&format=tsv&fields=date_created,date_modified,date_sequence_modified,version
```

**Comment by acragin** [comment]
`length('https://rest.uniprot.org/uniprotkb/search?query=accession:P05067&format=tsv&fields=date_created,date_modified,date_sequence_modified,version')
[1] 1`

**Comment by MohmedSoudy** [comment]
The request seems to work properly. In that regard, I will ask about your availability to organize a meeting to see exactly what is going on.
