### ISSUE TITLE
GetProteinAnnontate function cannot parse the content of Column-Function

### ISSUE THREAD

**Issue by panxiaoguang** [Proteomicslab57357/UniprotR#4]
```R
library(UniprotR)
library(httr)
ProteinAcc<-"P42293"
GetProteinAnnontate(ProteinAcc,"comment(CATALYTIC ACTIVITY)")
#Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
# no lines available in input
GetProteinAnnontate(ProteinAcc,c("feature(SIGNAL)","families"))
#                             Signal.peptide             Protein.families
#P42293 SIGNAL 1..26;  /evidence=ECO:0000255 Glycosyl hydrolase 43 family 
GetProteinAnnontate(ProteinAcc,c("feature(SIGNAL)","families","comment(CATALYTIC ACTIVITY)"))
#Error in curl::curl_fetch_memory(url, handle = handle) :  
```
> As seen in the code, once there is a call about the function column, the function will not work

**Comment by MohmedSoudy** [comment]
I think the problem is related to the internet connection as i run the same lines and have the output of the three lines.
```R
ProteinAcc<-"P42293"
GetProteinAnnontate(ProteinAcc,"comment(CATALYTIC ACTIVITY)")
"CATALYTIC ACTIVITY: Reaction=Endohydrolysis of (1->5)-alpha-arabinofuranosidic linkages in (1->5)-arabinans.; EC=3.2.1.99; Evidence={ECO:0000269|PubMed:20883454};
Levels: CATALYTIC ACTIVITY: Reaction=Endohydrolysis of (1->5)-alpha-arabinofuranosidic linkages in (1->5)-arabinans.; EC=3.2.1.99; Evidence={ECO:0000269|PubMed:20883454};"
GetProteinAnnontate(ProteinAcc,c("feature(SIGNAL)","families"))
"                             Signal.peptide             Protein.families
P42293 SIGNAL 1..26;  /evidence=ECO:0000255 Glycosyl hydrolase 43 family"
GetProteinAnnontate(ProteinAcc,c("feature(SIGNAL)","families","comment(CATALYTIC ACTIVITY)"))
"                             Signal.peptide             Protein.families
P42293 SIGNAL 1..26;  /evidence=ECO:0000255 Glycosyl hydrolase 43 family
                                                                                                                                                       Catalytic.activity
P42293 CATALYTIC ACTIVITY: Reaction=Endohydrolysis of (1->5)-alpha-arabinofuranosidic linkages in (1->5)-arabinans.; EC=3.2.1.99; Evidence={ECO:0000269|PubMed:20883454};"
```

**Comment by panxiaoguang** [comment]
> I think the problem is related to the internet connection as i run the same lines and have the output of the three lines.
> 
> ```r
> ProteinAcc<-"P42293"
> GetProteinAnnontate(ProteinAcc,"comment(CATALYTIC ACTIVITY)")
> "CATALYTIC ACTIVITY: Reaction=Endohydrolysis of (1->5)-alpha-arabinofuranosidic linkages in (1->5)-arabinans.; EC=3.2.1.99; Evidence={ECO:0000269|PubMed:20883454};
> Levels: CATALYTIC ACTIVITY: Reaction=Endohydrolysis of (1->5)-alpha-arabinofuranosidic linkages in (1->5)-arabinans.; EC=3.2.1.99; Evidence={ECO:0000269|PubMed:20883454};"
> GetProteinAnnontate(ProteinAcc,c("feature(SIGNAL)","families"))
> "                             Signal.peptide             Protein.families
> P42293 SIGNAL 1..26;  /evidence=ECO:0000255 Glycosyl hydrolase 43 family"
> GetProteinAnnontate(ProteinAcc,c("feature(SIGNAL)","families","comment(CATALYTIC ACTIVITY)"))
> "                             Signal.peptide             Protein.families
> P42293 SIGNAL 1..26;  /evidence=ECO:0000255 Glycosyl hydrolase 43 family
>                                                                                                                                                        Catalytic.activity
> P42293 CATALYTIC ACTIVITY: Reaction=Endohydrolysis of (1->5)-alpha-arabinofuranosidic linkages in (1->5)-arabinans.; EC=3.2.1.99; Evidence={ECO:0000269|PubMed:20883454};"
> ```

yes,it's the internet problem
