### ISSUE TITLE
Cannot convert UniProtKB AC/ID to UniProtKB 

### ISSUE THREAD

**Issue by goncik** [Proteomicslab57357/UniprotR#8]
Hi, 

I have a csv file with one column consist of UniProtKB AC/ID's as the following: 

1433B_HUMAN
1433E_HUMAN
1433F_HUMAN
1433G_HUMAN
1433S_HUMAN
1433T_HUMAN

And I want to convert my list into UniProtKB ie, P31946, P62258, Q04917... 

I tried doing this in R writing this: `ConvertID(ProteinAccList = substrate$Substrate_Uniprot_ID, ID_from = "UniProtKB_AC_ID" , ID_to = 'UniProtKB')`

It worked but returned an empty list:

From_UniProtKB_AC_ID To UniProtKB
1          1433B_HUMAN             
2          1433E_HUMAN             
3          1433F_HUMAN             
4          1433G_HUMAN             
5          1433S_HUMAN             
6          1433T_HUMAN             

I don't know if I do it wrong but I appreciate any help from your side because I have thousands of proteins to convert :) 

Many thanks!

**Comment by AliYoussef96** [comment]
Hi,

Uniprot DB use different names of IDs and accessions number, so in the code just pass ID_to = "ACC" instead of ID_to = "UniProtKB" and without ID_from.

```R
library("UniprotR")
ids <- c("1433B_HUMAN",
         "1433E_HUMAN",
         "1433F_HUMAN",
         "1433G_HUMAN",
         "1433S_HUMAN",
         "1433T_HUMAN")


ConvertID(ProteinAccList = ids , ID_to = 'ACC')
```

```R
  From_UniProtKB_AC_ID To ACC
1          1433B_HUMAN P31946
2          1433E_HUMAN P62258
3          1433F_HUMAN Q04917
4          1433G_HUMAN P61981
5          1433S_HUMAN P31947
6          1433T_HUMAN P27348
```
